WTCC_DB_Demo/MVCLayer/Models/CrudModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCLayer.Models
{
    public class CrudModel
    {
        public List<DriverModel> List { get; set; }
        public DriverModel EditObject { get; set; }
    }
}

WTCC_DB_Demo/MVCLayer/Models/DriverModel.cs
using System.ComponentModel.DataAnnotations;

namespace MVCLayer.Models
{
    public class DriverModel
    {
        [Display(Name = "Driver ID")]
        [Required]
        public int Driver_ID { get; set; }


        [Display(Name = "Driver Name 1")]
        [Required]
        [StringLength(14, MinimumLength = 3)]
        public string Driver_Name1 { get; set; }

        [Display(Name = "Driver Name 2")]
        [Required]
        [StringLength(14, MinimumLength = 3)]
        public string Driver_Name2 { get; set; }

        [Display(Name = "Driver Age:")]
        [Required]
        public int Driver_Age { get; set; }

        [Display(Name = "Driver Points:")]
        [Required]
        [Range(minimum: 0, maximum: 99, ErrorMessage = "Point must be between 0 and 99")]
        public int Driver_Points { get; set; }
    }
}

WTCC_DB_Demo/MVCLayer/Controllers/CrudController.cs
using AutoMapper;
using BusinessLogic;
using MVCLayer.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Data;

namespace MVCLayer.Controllers
{
    public class CrudController : Controller
    {
        IMapper mapper;
        Logic logic;
        CrudModel model;

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            mapper = DTO.AutoMapperConfig.GetMapper();

            logic = new Logic();
            model = new CrudModel();
            model.EditObject = new DriverModel();
            model.List = mapper.Map<IQueryable<Data.DRIVER>, List<Models.DriverModel>>(logic.GetDrivers());

        }

        private DriverModel GetDriverModel(int id)
        {
            return mapper.Map<Data.DRIVER, Models.DriverModel>(logic.GetOneDriver(id));
        }

        // GET: Crud
        public ActionResult Index()
        {
            ViewData["TargetAction"] = "AddNewDriver";
            return View("CrudIndex", model);
        }

        public ActionResult Details(int id)
        {
            return View("CrudDatasheet", GetDriverModel(id));
        }

        public ActionResult Edit(int id)
        {
            ViewData["TargetAction"] = "Edit";
            model.EditObject = GetDriverModel(id);
            return View("CrudIndex", model);
        }

        [HttpPost]
        public ActionResult Edit(DriverModel model)
        {
            if (ModelState.IsValid && model != null)
            {
                logic.ModifyDriver(model.Driver_ID, model.Driver_Name1, model.Driver_Name2, model.Driver_Age, model.Driver_Points);
                TempData["result"] = "Edit successful!";
            }
            else
                TempData["result"] = "Edit unsuccessful";
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public ActionResult AddNewDriver(DriverModel model)
        {
            if (ModelState.IsValid && model != null)
            {
                Data.DRIVER d = mapper.Map<Models.DriverModel, Data.DRIVER>(model);
                d.DRIVER_ID = logic.GetNextDriverID();
                logic.AddDriver(d);
                TempData["result"] = "New driver added successfully!";
            }
            else
                TempData["result"] = "Failed to add new Driver";
            return RedirectToAction("Index");
        }

        public ActionResult Remove(int id)
        {
            try
            {
                logic.DelDriver(id);
                TempData["result"] = "Driver was deleted.";
            }
            catch (DbUpdateException)
            {
                TempData["result"] = "An error occured while deleting driver.";
            }
            catch (ArgumentException)
            {
                TempData["result"] = "An error occured while deleting driver.";
            }
            return RedirectToAction("Index");
        }
    }
}

WTCC_DB_Demo/MVCLayer/Controllers/DriverServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLayer.Controllers
{
    public class DriverServiceController : Controller
    {
        // GET: DriverService
        public ActionResult Index()
        {
            return View();
        }
    }
}

WTCC_DB_Demo/MVCLayer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLayer.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WTCC_DB_Demo/MVCLayer/Controllers/JsonController.cs
using AutoMapper;
using BusinessLogic;
using Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Http;

namespace MVCLayer.Controllers
{
    public class JsonController : ApiController
    {
        // GET: Test


        Logic logic;
        IMapper mapper;

        public JsonController()
        {
            logic = new Logic();
            mapper = DTO.AutoMapperConfig.GetMapper();
        }

        [HttpGet]
        [ActionName("driver")]
        public Models.DriverModel GetSingleDriver(int id)
        {
            return mapper.Map<Data.DRIVER, Models.DriverModel>(logic.GetOneDriver(id));
        }

        [HttpGet]
        [ActionName("listdrivers")]
        public List<string> GetEveryDriver()
        {
            List<string> s = new List<string>();
            DRIVER[] array =  logic.GetDrivers().ToArray();
            foreach (DRIVER driver in array)
            {
                StringBuilder sb = new StringBuilder();
                sb.AppendFormat("<br>Név: {0} {1} ", driver.DRIVER_NAME1, driver.DRIVER_NAME2);
                sb.AppendFormat("Életkor: {0}, pontszáma: {1}",driver.DRIVER_AGE, driver.DRIVER_POINTS);
                s.Add(sb.ToString());
            }

            return s;
        }

        /*
         [HttpGet]
        [ActionName("listdrivers")]
        public List<DTO.Driver> GetEveryDriver()
        {
            return mapper.Map<IQueryable<Data.DRIVER>, List<DTO.Driver>>(logic.GetDrivers());
        }
         
         */



    }
}

WTCC_DB_Demo/MVCLayer/Views/Crud/CrudDatasheet.cshtml
@model MVCLayer.Models.DriverModel
@{
    ViewBag.Title = "CrudDatasheet";
}

<h2>Detailed Driver Information</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Driver_ID)</td>
        <td>@Html.DisplayFor(m => m.Driver_ID)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Driver_Name1)</td>
        <td>@Html.DisplayFor(m => m.Driver_Name1)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Driver_Name2)</td>
        <td>@Html.DisplayFor(m => m.Driver_Name2)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Driver_Age)</td>
        <td>@Html.DisplayFor(m => m.Driver_Age)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Driver_Points)</td>
        <td>@Html.DisplayFor(m => m.Driver_Points)</td>
    </tr>
</table>

WTCC_DB_Demo/MVCLayer/Views/Crud/CrudEdit.cshtml
@model MVCLayer.Models.DriverModel

<h2>Add/Edit Drivers</h2>

@using (Html.BeginForm(ViewData["TargetAction"].ToString(), "Crud"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Driver_ID)

    <div class="editor-label">@Html.LabelFor(m => m.Driver_Name1)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Driver_Name1)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Driver_Name2)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Driver_Name2)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Driver_Age)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Driver_Age)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Driver_Points)</div>
        <div class="editor-field">@Html.EditorFor(m => m.Driver_Points)</div>

    <input type="submit" value="SEND" />

}

WTCC_DB_Demo/MVCLayer/Views/Crud/CrudIndex.cshtml
@model MVCLayer.Models.CrudModel

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}


@{
    ViewBag.Title = "CrudIndex";
}

<h2>Driver Site</h2>

@Html.Partial("CrudEdit", Model.EditObject)

@Html.Partial("CrudList", Model.List)

WTCC_DB_Demo/MVCLayer/Views/Crud/CrudList.cshtml
@model IEnumerable<MVCLayer.Models.DriverModel>

<p style="color:red">@TempData["result"]</p>

@if (Model.Count() == 0)
{
    <p>NO Data in DB</p>
}
else
{
    <table>
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(m => m.Driver_ID)</th>
                <th>@Html.DisplayNameFor(m => m.Driver_Name1)</th>
                <th>@Html.DisplayNameFor(m => m.Driver_Name2)</th>
                <th>@Html.DisplayNameFor(m => m.Driver_Age)</th>
                <th>@Html.DisplayNameFor(m => m.Driver_Points)</th>
                <th>Datasheet</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(m => item.Driver_ID)</td>
                    <td>@Html.DisplayFor(m => item.Driver_Name1)</td>
                    <td>@Html.DisplayFor(m => item.Driver_Name2)</td>
                    <td>@Html.DisplayFor(m => item.Driver_Age)</td>
                    <td>@Html.DisplayFor(m => item.Driver_Points)</td>
                    <td>@Html.ActionLink("Details", "Details", new { id = item.Driver_ID })</td>
                    <td>@Html.ActionLink("Edit", "Edit", new { id = item.Driver_ID })</td>
                    <td>@Html.ActionLink("Remove", "Remove", new { id = item.Driver_ID })</td>
                </tr>
            }
        </tbody>
    </table>
}

WTCC_DB_Demo/MVCLayer/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WTCC_DB_Demo/MVCLayer/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WTCC_DB_Demo/MVCLayer/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<h1>Hello world!</h1>
<!--
<div clyass="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>
    -->

WTCC_DB_Demo/MVCLayer/Views/Json/JsonIndex.cshtml
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

@{
    ViewBag.Title = "JsonIndex";
}

<h2>Driver list generated with JSON</h2>

@Html.Partial("ListDriversWithJson")

WTCC_DB_Demo/MVCLayer/Views/Json/ListDriversWithJson.cshtml
<a href="/api/json/listdrivers" target="_blank">List Drivers with JSON</a>

WTCC_DB_Demo/MVCLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" Data-toggle="collapse" Data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Drivers Crud", "Index", "Crud")</li>
                    <li><a href="/api/json/listdrivers" target="_blank">List Drivers with JSON</a></li>
                    <li>@Html.ActionLink("Drivers JSON(in progress)", "Index", "Json")</li>
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>